name: Run /test/

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: inflated-goboscript/gstest@v0.1.0